/* Middleware Actions */

/* Device Actions */

/* Metadata Actions */
export const ARCHIVE_ORGANIZAION_SUCESS = "ARCHIVE_ORGANIZAION_SUCESS";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";

export const ARCHIVE_WEBSITE_SUCESS = "ARCHIVE_WEBSITE_SUCESS";
export const CREATE_WEBSITE_SUCCESS = "CREATE_WEBSITE_SUCCESS";
export const DELETE_WEBSITE_SUCCESS = "DELETE_WEBSITE_SUCCESS";
export const GET_WEBSITE_SUCCESS = "GET_WEBSITE_SUCCESS";
export const GET_WEBSITES_SUCCESS = "GET_WEBSITES_SUCCESS";
export const UPDATE_WEBSITE_SUCCESS = "UPDATE_WEBSITE_SUCCESS";

/* Search Actions */
export const RESET_SEARCH_SUCCESS = "RESET_SEARCH_SUCCESS";
export const UPDATE_SEARCH_SUCCESS = "UPDATE_SEARCH_SUCCESS";

/* User Actions */
